// <auto-generated />
using DemoMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DemoMVC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240924032446_Create_Table_LopHoc")]
    partial class Create_Table_LopHoc
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("DemoMVC.Models.Employee", b =>
                {
                    b.Property<string>("StudenID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tuoi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("StudenID");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("DemoMVC.Models.LopHoc", b =>
                {
                    b.Property<string>("TenLop")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaLop")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TenLop");

                    b.ToTable("LopHoc");
                });
#pragma warning restore 612, 618
        }
    }
}
